### ISSUE TITLE
Support Enterprise Grid

### ISSUE THREAD

**Issue by akiakaba** [sisisin/chattun#33]
<img width="482" alt="スクリーンショット 2021-04-24 9 23 05" src="https://user-images.githubusercontent.com/11155356/115941102-f8df2280-a4de-11eb-8b7e-7a69a48ff743.png">

**Comment by akiakaba** [comment]
Deep Linking doesn't work also.

**Comment by sisisin** [comment]
resolved at 57ef298f81ba8b57f027b16200205bacb4a82345
